config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { registrations: "registrations"}

resources :items do
  collection do
    post :index
  end
end

resources :subcats

resources :categories

root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true #, uniqueness: { case_sensitive: false }, length: {maximum: 50}
  validates :body, presence: true #, uniqueness: { case_sensitive: false }, length: {maximum: 100}

  has_many :subcats
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true #, uniqueness: { case_sensitive: false }, length: {maximum: 50}
  validates :body, presence: true

  belongs_to :user
  belongs_to :subcat
  belongs_to :category
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/subcat.rb
class Subcat < ApplicationRecord

  has_many :items
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!, except: [:show, :index]
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.order("created_at DESC")
  end

  def new
    @category = Category.new
  end
 
  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Object successfully created"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def update
    @category = Category.find_by id: params[:id]
    if @category.update category_params
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = t('.success')
    redirect_to root_path
  end
  
  def show
    @category = Category.find_by id: params[:id]
    @subcats = Subcat.where(category_id: params[:category_id])
  end
  
  private

  def category_params
    params.require(:category).permit(:title, :body)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    #@items = Item.all
    @pagy, @items = pagy_countless(Item.order(created_at: :desc), items: 36)
    respond_to do |format|
      format.html #GET
      format.turbo_stream #POST
    end
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find_by id: params[:id]
  end
  
  def update
    @item = Item.find_by id: params[:id]
    if @item.update item_params
      redirect_to root_path
    else
      render :edit
    end
  end

  def delete
  end

  def create
    @item = current_user.items.build item_params
    if @item.save
      flash[:success] = "Object successfully created"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def show
    @item = Item.find_by id: params[:id]
    @subcat = @item.subcat
    @category = @subcat.category
  end
  
  private

  def item_params
    params.require(:item).permit(:title, :body, :price, :category_id, :subcat_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
    def after_sign_up_path_for(resource)
      root_path
    end
end

app/controllers/subcats_controller.rb
class SubcatsController < ApplicationController

  def index
    @subcat = Subcat.order("created_at DESC")
  end

  def edit
    @subcat = subcat.find_by id: params[:id]
  end

  def new
    @subcat = Subcat.new
  end
 
  def create
    @subcat = Subcat.new subcat_params
    if @subcat.save
      flash[:success] = "Object successfully created"
      redirect_to @subcat
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end
  
  def show
    @subcat = Subcat.find_by id: params[:id]
    @items = Item.where(subcat_id: params[:subcat_id])
    @category = @subcat.category
  end
  
  private

  def subcat_params
    params.require(:subcat).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  include Pagy::Frontend

  def navigation_at()
    render partial: "navbar/navbar"
  end

  def mover_at()
    render partial: "shared/top"
  end

  def section_at()
    render partial: "pages/sections"
  end

  def leftbar_at()
    render partial: "navbar/leftbar"
  end

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_categories.html.erb
<% @categories.each do |category| %>
<div>
  <%= link_to category_path(category) do %>
    <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1">
       <%= image_tag src="https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg" %>
    </div>
  <% end %>
  <h3 class="mt-6 text-base text-gray-900"><%= category.title %></h3>
  <p class="text-sm text-gray-500"><%= category.body %></p>
</div>
<% end %>

app/views/categories/_category.html.erb
<div>
  <%= link_to category_path(category) do %>
    <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1">
       <%= image_tag src="https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg" %>
    </div>
  <% end %>
  <h3 class="mt-6 text-base text-gray-900"><%= category.title %></h3>
  <p class="text-sm text-gray-500"><%= category.body %></p>
</div>

app/views/categories/index.html.erb
<% mover_at %>
<% navigation_at %>
<div class="bg-gray-100">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-2xl py-16 sm:py-24 lg:max-w-none lg:py-32">
      <h2 class="text-2xl font-bold text-gray-900">Categories</h2>
      <div class="mt-6 space-y-12 gap-y-12 gap-x-8 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
        <%= render @categories %>
        <%= yield :main_top %>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<% mover_at %>
<% navigation_at %>
<div class="bg-gray-100">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-2xl py-16 sm:py-24 lg:max-w-none lg:py-32">
      <h2 class="text-2xl font-bold text-gray-900">Subcategories</h2>
      <div class="mt-6 space-y-12 gap-y-12 gap-x-8 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
        <%= render @category.subcats %>
        <%= yield :main_top %>
      </div>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with model: @item do |f| %>
<p class="mb-4">
<%= f.label :title %>
<%= f.text_field :title, required: true, minlength: 5, class:"inline-flex py-2 px-3 hover:bg-slate-200 rounded" %>
</p>

<p class="mb-4">
<%= f.label :body %>
<%= f.text_field :body, required: true, minlength: 10, class:"inline-flex py-2 px-3 hover:bg-slate-200 rounded" %>
</p>

<p class="mb-4">
<%= f.label :price %>
<%= f.text_field :price, required: true, minlength: 1, class:"inline-flex py-2 px-3 hover:bg-slate-200 rounded" %>
</p>

<p class="mb-4">
<%= f.label :category_id %>
<%= f.select :category_id, Category.pluck(:title, :id), class:"inline-flex py-2 px-3 hover:bg-slate-200 rounded" %>
</p>

<p class="mb-4">
<%= f.label :subcat_id %>
<%= f.select :subcat_id, Subcat.pluck(:title, :id), class:"inline-flex py-2 px-3 hover:bg-slate-200 rounded" %>
</p>


<%= f.submit "Done", class:"mt-4 px-4 py-3  leading-6 text-base rounded-md border border-transparent text-white focus:outline-none bg-blue-500 text-blue-100 hover:text-white focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 cursor-pointer inline-absolute items-center w-full justify-center items-center font-sm focus:outline-none" %>

<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">

<!--item image content begin-->
  <div class="aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-w-7 xl:aspect-h-8 drop-shadow-lg">
    <div x-data="carousel()" class="relative">
      <%= link_to item do %>
      <img class="h-64 w-full object-cover object-center" :src="images[selected]" alt="mountains"/>
      <% end %>
      <button @click="if (selected > 0 ) {selected -= 1} else { selected = images.length - 1 }" class="absolute inset-y-0 left-0 px-2 py-[25%] h-full w-10 group hover:bg-gray-400 hover:bg-opacity-50 cursor-pointer">
        <span class="hidden group-hover:block text-gray-50">
          &larr;
        </span>
      </button>
      <button @click="if (selected < images.length - 1  ) {selected += 1} else { selected = 0 }" class="absolute inset-y-0 right-0 px-2 py-[25%] h-full w-10 group hover:bg-gray-400 hover:bg-opacity-50 cursor-pointer">
        <span class="hidden group-hover:block text-gray-50">
          &rarr;
        </span>
      </button>

      <div class="absolute bottom-0 w-full p-4 flex justify-center space-x-2">
        <template x-for="(image,index) in images" :key="index">
          <button @click="selected = index" :class="{'bg-gray-300': selected == index, 'bg-gray-500': selected != index}" class="h-2 w-2 rounded-full hover:bg-gray-300 ring-2 ring-gray-300">
          </button>
        </template>
      </div>
    </div>
    <script>
      const carousel = () => {
        return {
          selected: 0,
          images: [
            "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
            "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
            "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80",
            "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
            "https://images.unsplash.com/photo-1485160497022-3e09382fb310?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
            "https://images.unsplash.com/photo-1472791108553-c9405341e398?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2137&q=80"
          ]
        };
      };
    </script>
  </div>
  <!--item image content end-->

    <h3 class="mt-4 text-sm text-gray-700"><%= item.title %></h3>
    <h3 class="mt-4 text-sm text-gray-700"><%= item.id %></h3>

  <div class="grid grid-cols-2 mt-2">
    <p class="mt-1 text-lg font-medium text-gray-800">US $ <%= item.price %></p>
    <button type="button" class="rounded-full inline-block px-6 py-2.5 bg-blue-500 text-white font-medium text-xs leading-tight uppercase hover:bg-blue-700 focus:bg-blue-700 focus:outline-none focus:ring-0 active:bg-blue-800 transition duration-150 ease-in-out">Add to cart</button>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %>

app/views/items/index.html.erb
<% mover_at %>
<% navigation_at %>
<div class="bg-gray-100">
  <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
    <h2 class="text-2xl font-bold text-gray-900 mb-8">iTems</h2>
    <div id="items" class="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
      <%= render @items %>
    </div>
      <%= turbo_frame_tag :pagination, loading: :lazy, src: items_path(format: :turbo_stream) %> <!--Stram more items-->
      <%= yield :main_top %>
  </div>
</div>

app/views/items/index.turbo_stream.erb
<%= turbo_stream.append :items do %>
  <%= render @items, collection: @items %>
<% end %>


<% if @pagy.next.present? %>
  <%= turbo_stream.replace :pagination do %>
    <%= turbo_frame_tag :pagination, loading: :lazy, src: items_path(format: :turbo_stream, page: @pagy.next) do %>
    <div class="flex justify-center mt-6">
      <p class="text-lg font-bold text-gray-700">Loading...</p>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/items/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>Simpleshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= yield :main_navbar %>
    <%= yield %>
  </body>
</html>

app/views/navbar/_leftbar.html.erb
<%= provide :leftbar do %>
<aside class="flex-shrink-0 w-64 flex flex-col border-r transition-all duration-300 bg-gray-100" :class="{ '-ml-64': !sidebarOpen }">
  <nav class="flex-1 flex flex-col bg-gray-100 fixed z-10 w-64 h-full top-0 divide-y">
    <p class="flex items-center text-lg italic py-4 px-6 h-12 overflow-hidden text-gray-700 text-ellipsis whitespace-nowrap rounded hover:text-gray-900 bg-gray-100  ease-in-out mb-4 mt-2"> Catalogue name </p>
    <div id="catalogue" class="overflow-scroll">

      <ul class="shadow-box">	
      <% Category.all.each do |category|%>				
        <li class="relative border-b border-gray-200" x-data="{selected:null}">
          <button type="button" class="w-full px-8 py-6 text-left" @click="selected !== 1 ? selected = 1 : selected = null">
            <div class="flex items-center justify-between">
              <span class="flex items-center text-sm py-4 px-6 h-12 overflow-hidden text-gray-700 text-ellipsis whitespace-nowrap rounded  ease-in-out">
                  <%= category.title %>            
              </span>
            </div>
          </button>
          <div class="relative overflow-hidden transition-all max-h-0 duration-700" style="" x-ref="container1" x-bind:style="selected == 1 ? 'max-height: ' + $refs.container1.scrollHeight + 'px' : ''">
            <div class="p-6">
                <% category.subcats.each do |subcat| %>
                  <%= link_to subcat.title, subcat_path(subcat), class:"flex items-center text-sm py-4 px-6 h-12 overflow-hidden text-gray-700 text-ellipsis whitespace-nowrap rounded bg-gray-200 mb-2 ease-in-out" %>
                <% end %>
            </div>
          </div>
        </li>
      <% end %>
      </ul>
    </div>
    <!--Close Button-->

    <button x-on:click="sidebarOpen = !sidebarOpen" class="absolute top-0 right-0 bottom-0 left-0">   
      <!-- open icon -->    
      <svg x-show="!sidebarOpen" xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 absolute top-4 left-64 bg-gray-100 rounded-r-lg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
      </svg>    
      <!-- close icon -->   
      <svg x-show="sidebarOpen" xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 absolute top-4 left-64 bg-gray-100 rounded-r-lg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
      </svg>
    </button>
  </nav>
</aside>
<% end %>

app/views/navbar/_navbar.html.erb
<% section_at %>
<% leftbar_at %>
<%= provide :main_navbar do %>

<!--Menu-->

  <div class="bg-cover" x-data="{ openMenu: false, sidebarOpen: false, subbarOpen: false}"
    :class="openMenu ? 'overflow-hidden' : 'overflow-visible'">

    <style>
      [x-cloak] {
        display: none !important;
      }
    </style>

      <header class="flex justify-between relative z-20 items-center bg-white drop-shadow-sm py-4 px-8">
        <button x-on:click="sidebarOpen = !sidebarOpen" class="relative border-0 w-10 h-10 rounded-full drop-shadow-md bg-white text-gray-700 text-3xl font-bold justify-center">

          <!-- open icon -->

          <svg x-show="!sidebarOpen" xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
          </svg>

          <!-- close icon -->

          <svg x-show="sidebarOpen" xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
          </svg>
        </button>

        <!--Mobile Menu Toggle-->

        <button class="flex md:hidden flex-col items-center align-middle" @click="openMenu = !openMenu"
          :aria-expanded="openMenu" aria-controls="mobile-navigation" aria-label="Navigation Menu">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <span class="text-xs">Menu</span>
        </button>

        <!--Navigation-->

        <nav class="hidden md:flex">
          <%= yield :sections %>
        </nav>
        
      </header>

      <%= yield :leftbar %>

      <!--Navigation Mobile-->

      <nav id="mobile-navigation" class="fixed top-0 right-0 bottom-0 left-0 backdrop-blur-sm z-30"
        :class="openMenu ? 'visible' : 'invisible' " x-cloak>
        
        <%= yield :mobile_section %>

        <!--Close Button-->

        <button class="absolute top-0 right-0 bottom-0 left-0" @click="openMenu = !openMenu" :aria-expanded="openMenu"
          aria-controls="mobile-navigation" aria-label="Close Navigation Menu">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 absolute top-2 left-2" fill="none" viewBox="0 0 24 24"
            stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </nav>
  </div>

<!--End Menu-->

<% end %>

app/views/pages/_sections.html.erb
<!--Desctop Links Begin-->
<%= provide :sections do %>          
<ul class="flex flex-row gap-2">
  <li>
    <%= link_to "Home", root_path, class:"inline-flex py-2 px-3 hover:bg-slate-200 rounded" %>
  </li>
  <li>
    <a href="#" class="inline-flex py-2 px-3 hover:bg-slate-200 rounded" aria-current="true">More</a>
  </li>
  <li>            
    <%= link_to "Categories", categories_path, class:"inline-flex py-2 px-3 hover:bg-slate-200 rounded" %>
  </li>
  <% if user_signed_in? %>
  <li>
    <%= link_to "Log out", destroy_user_session_path, data:{ "turbo-method": :delete }, class:"inline-flex py-2 px-3 hover:bg-slate-200 rounded" %>
  </li>
  <% else %>
  <li>
    <%= link_to "Log in", new_user_session_path, class:"inline-flex py-2 px-3 hover:bg-slate-200 rounded" %>
  </li>
  <% end %>
</ul>
<% end %>
<!--Desctop Links End-->

<!--Mobile Links Begin-->
<%= provide :mobile_section do %>
<ul class="absolute top-0 right-0 bottom-0 w-10/12 py-4 bg-white drop-shadow-2xl z-10 transition-all"
  :class="openMenu ? 'translate-x-0' : 'translate-x-full'">
  <li class="border-b border-inherit">
    <a href="#" class="block p-4" aria-current="true">Home</a>
  </li>
  <li class="border-b border-inherit">
    <a href="#" class="block p-4">About</a>
  </li>
  <li class="border-b border-inherit">
    <%= link_to "Category", categories_path, class:"block p-4" %>
  </li>
  <% if user_signed_in? %>
  <li class="border-b border-inherit">
    <%= link_to "Log out", destroy_user_session_path, data:{ "turbo-method": :delete }, class:"block p-4" %>
  </li>
  <% else %>
  <li class="border-b border-inherit">
    <%= link_to "Log in", new_user_session_path, class:"block p-4" %>
  </li>
  <% end %>
</ul>
<% end %>
<!--Mobile Links End-->

app/views/shared/_top.html.erb
<%= provide :main_top do %>
<button id="to-top-button" onclick="goToTop()" title="Go To Top"
        class="hidden fixed z-90 bottom-8 right-8 border-0 w-16 h-16 rounded-full drop-shadow-md bg-white text-blue-500 text-3xl font-bold">&uarr;</button>

<!-- Javascript code -->
<script>
    var toTopButton = document.getElementById("to-top-button");
    // When the user scrolls down 200px from the top of the document, show the button
    window.onscroll = function () {
        if (document.body.scrollTop > 200 || document.documentElement.scrollTop > 200) {
            toTopButton.classList.remove("hidden");
        } else {
            toTopButton.classList.add("hidden");
        }
    }
    // When the user clicks on the button, scroll to the top of the document
    function goToTop() {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }
</script>
<% end %>

app/views/subcats/_subcat.html.erb
<div>
  <%= link_to subcat_path(subcat) do %>
    <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1">
       <%= image_tag src="https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg" %>
    </div>
  <% end %>
  <h3 class="mt-6 text-base text-gray-900"><%= subcat.title %></h3>
</div>

app/views/subcats/_subcats.html.erb
<% @category.subcats.each do |subcat| %>
<div>

    <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1">
       <%= image_tag src="https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg" %>
    </div>

  <h3 class="mt-6 text-base text-gray-900"><%= subcat.title %></h3>
</div>
<% end %>

app/views/subcats/show.html.erb
<% mover_at %>
<% navigation_at %>
<div class="bg-gray-100">
<div class="pt-6">
  <nav>
    <ol role="list" class="mx-auto flex max-w-2xl items-center space-x-2 px-4 sm:px-6 lg:max-w-7xl lg:px-8">
      <li>
        <div class="flex items-center">
          <%=link_to @category.title, @category, class:"mr-2 text-sm font-medium text-gray-900" %>
          <svg width="16" height="20" viewBox="0 0 16 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" class="h-5 w-4 text-gray-300">
            <path d="M5.697 4.34L8.98 16.532h1.327L7.025 4.341H5.697z" />
          </svg>
        </div>
      </li>
      <li>
        <div class="flex items-center">
          <%=link_to @subcat.title, @subcat, class:"mr-2 text-sm font-medium text-gray-900" %>
          <svg width="16" height="20" viewBox="0 0 16 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" class="h-5 w-4 text-gray-300">
            <path d="M5.697 4.34L8.98 16.532h1.327L7.025 4.341H5.697z" />
          </svg>
        </div>
      </li>
    </ol>
  </nav>
  <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
    <div class="mt-4 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
        <%= render @subcat.items %> 
        <%= yield :main_top %>
    </div>
  </div>
</div>
</div>